image: samueldebruyn/debian-git 

pipelines:
  default:
    - step:
        script:
          - apt-get -qq update
          - apt-get install git-ftp
          - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://109.199.121.179/