<?php

$data = array( 
    'public' => array(
        'kmvg_products' ,
        'kmvg_wips' ,
        'sharefb' ,
        'share_email' ,
        'kcat',
        'ksm_facet',
        'fvii',
        ),
    
    'private' => array(
        'post_wall',
        'post_wall_comment',
        'wiu',
        'ciu',
        'plike',
        'clike',
        'follow',
        'ksm_edit_profile',
        'ksm_update_settings',
        'uau', 
        'uwipu',
        'ksm_add_wip',
        'sharefb',
        'sharefb',
        'share_email',
        'kgdfuh',
        'share_email',
        'kmvg_products',
        'kmvg_wips', 
        'kmvg_wips', 
        'pub_step_validate',
        'pub_submit', 
        'pub_upl_sa', 
        'pubimgu',
        'kajl',
        'kcat', 
        'kcat', 
        'favorite', 
        'dd_messages',
        'delete_messages',
        'read_messages',
        'users_suggest',
        'softwares_suggest', 
        'skills_suggest', 
        'fvii',
        'kcus',
        'dd_notifications', 
        'delete_notifications',
        'post_options',
        'ksm_facet',
        'ks3uplsuc'
        )
);